# Generated by Django 3.0.7 on 2020-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeassistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="topic_type",
            field=models.CharField(
                choices=[("subscribe", "Subscribe"), ("publish", "Publish")],
                default="publish",
                max_length=16,
            ),
        ),
    ]
