# Generated by Django 3.0.6 on 2020-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeassistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='default_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
