# Generated by Django 3.0.6 on 2020-06-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homeassistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField()),
                ("name", models.CharField(max_length=32)),
                (
                    "type_value",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                        ],
                        default="bool",
                        max_length=16,
                    ),
                ),
                (
                    "minimal",
                    models.FloatField(
                        default=0,
                        help_text="for string length; for numerics min. value",
                    ),
                ),
                (
                    "maximal",
                    models.FloatField(
                        default=255,
                        help_text="for string length; for numerics max. value",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GismoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("3.1", "3.1"), ("3.3", "3.3")],
                        default="3.3",
                        max_length=16,
                    ),
                ),
                (
                    "pref_status_cmd",
                    models.IntegerField(
                        choices=[(10, "Dp Query"), (13, "Control New")], default=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="HAOverwrite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "tuya_type_value",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
                ("tuya_value", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "dp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tuya.Dp"
                    ),
                ),
                (
                    "topic_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeassistant.TopicValue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gismo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("deviceid", models.CharField(max_length=64, unique=True)),
                ("localkey", models.CharField(max_length=64, unique=True)),
                ("ip", models.GenericIPAddressField()),
                ("ha_discovery", models.BooleanField()),
                ("tuya_discovery", models.BooleanField()),
                (
                    "gismo_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuya.GismoModel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dp",
            name="gismo_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tuya.GismoModel"
            ),
        ),
        migrations.AddField(
            model_name="dp",
            name="ha_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="homeassistant.Component",
            ),
        ),
    ]
