# Generated by Django 3.0.6 on 2020-05-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('protocol', models.CharField(choices=[('3.1', '3.1'), ('3.3', '3.3')], default='3.3', max_length=16)),
                ('deviceid', models.CharField(max_length=64)),
                ('localkey', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('hass_discovery', models.BooleanField()),
                ('tuya_discovery', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dpstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('valuetype', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('str', 'String')], default='bool', max_length=16)),
                ('range_min', models.IntegerField(default=0)),
                ('range_max', models.IntegerField(default=255)),
                ('discoverytype', models.CharField(choices=[('light', 'Light'), ('switch', 'Switch'), ('sensor', 'Sensor'), ('binary_sensor', 'Binary Sensor')], default='light', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('value', models.CharField(max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuya.Device')),
                ('dpstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuya.Dpstype')),
            ],
        ),
    ]
