# Generated by Django 3.0.7 on 2020-06-14 08:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homeassistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(help_text="The number of the data point.")),
                ("name", models.CharField(help_text="Common name.", max_length=32)),
                (
                    "type_value",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                        ],
                        default="bool",
                        help_text="Output type of the data point.",
                        max_length=16,
                    ),
                ),
                (
                    "minimal",
                    models.FloatField(
                        default=0,
                        help_text="For string length; for numerics min. value.",
                    ),
                ),
                (
                    "maximal",
                    models.FloatField(
                        default=255,
                        help_text="For string length; for numerics max. value.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HAOverwrite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=256)),
                (
                    "tuya_type_value",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                            ("float", "Float"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
                ("tuya_value", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "dp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tuya.Dp"
                    ),
                ),
                (
                    "topic_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeassistant.TopicValue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GismoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("3.1", "3.1"), ("3.3", "3.3")],
                        default="3.3",
                        max_length=16,
                    ),
                ),
                (
                    "pref_status_cmd",
                    models.IntegerField(
                        choices=[(10, "Dp Query"), (13, "Control New")], default=10
                    ),
                ),
                (
                    "ha_component",
                    models.ForeignKey(
                        blank=True,
                        help_text="Device type for Home Assistant",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeassistant.Component",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gismo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Common name for device.", max_length=32, unique=True
                    ),
                ),
                ("deviceid", models.CharField(max_length=64, unique=True)),
                ("localkey", models.CharField(max_length=64)),
                ("ip", models.GenericIPAddressField(unique=True)),
                (
                    "ha_discovery",
                    models.BooleanField(
                        help_text="Send discovery messages to Home Assistant."
                    ),
                ),
                (
                    "tuya_discovery",
                    models.BooleanField(
                        help_text="Send discovery messages to TuyaGateway."
                    ),
                ),
                (
                    "gismo_model",
                    models.ForeignKey(
                        help_text="Configuration for the device.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuya.GismoModel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DpName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for the dat point.", max_length=32
                    ),
                ),
                (
                    "dp",
                    models.ForeignKey(
                        help_text="Data point of the device.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuya.Dp",
                    ),
                ),
                (
                    "gismo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tuya.Gismo"
                    ),
                ),
                (
                    "gismo_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuya.GismoModel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dp",
            name="gismo_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tuya.GismoModel"
            ),
        ),
        migrations.AddField(
            model_name="dp",
            name="ha_component",
            field=models.ForeignKey(
                help_text="Device type for Home Assistant",
                on_delete=django.db.models.deletion.CASCADE,
                to="homeassistant.Component",
            ),
        ),
        migrations.AddField(
            model_name="dp",
            name="ha_topic",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="ha_component",
                chained_model_field="component",
                limit_choices_to={"topic_type": "publish"},
                on_delete=django.db.models.deletion.CASCADE,
                to="homeassistant.Topic",
            ),
        ),
    ]
