# Generated by Django 3.0.7 on 2020-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuya", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gismomodel",
            name="api_model",
            field=models.CharField(default="", max_length=32),
        ),
    ]
