# Generated by Django 3.0.6 on 2020-05-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dps',
            name='value',
        ),
    ]
